name: 完整同步海豚源

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 下载海豚源的原始文件，直接保存到最终输出路径
    - name: Fetch target file
      run: |
        mkdir -p datas
        curl -L "https://raw.githubusercontent.com/FGBLH/GHK/refs/heads/main/海豚.json" -o datas/local_config.json

    # 运行 Python 脚本进行格式规范检查（确保中文和缩进排版漂亮）
    - name: Format JSON
      run: |
        python modify_config.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "文件没有变化，无需更新。"
        else
          git commit -m "原封不动完整同步: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        fi
